file_format: "1"
id: skully
name: The Skully 
type: shield
url: https://github.com/roanmertens/zmk-config-skully
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - skully_left
  - skully_right
